-- Supabase migration for Ivoire Tour Village
-- Run in Supabase SQL Editor

-- Extensions
create extension if not exists postgis;

-- Users ( Supabase Auth handles most, but we keep a public profile row )
create table public.users (
  id uuid references auth.users(id) primary key,
  name text,
  email text unique not null,
  password_hash text not null,
  is_admin boolean default false,
  email_verified_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.users enable row level security;

create policy "Users can read own profile"
  on public.users for select
  using ( auth.uid() = id );

create policy "Users can update own profile"
  on public.users for update
  using ( auth.uid() = id );

-- Villages
create table public.villages (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  nom text not null,
  region text,
  resume text,
  histoire text,
  patrimoine text,
  activites jsonb default '[]'::jsonb,
  hebergements jsonb default '[]'::jsonb,
  artisans jsonb default '[]'::jsonb,
  evenements jsonb default '[]'::jsonb,
  latitude numeric(9,6),
  longitude numeric(9,6),
  image text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.villages enable row level security;

create policy "Allow public read villages"
  on public.villages for select
  using ( true );

-- Offres
create table public.offres (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  titre text not null,
  village_id bigint not null references public.villages(id) on delete cascade,
  description text,
  duree text,
  prix integer,
  places_disponibles integer,
  difficulte text,
  inclus jsonb default '[]'::jsonb,
  non_inclus jsonb default '[]'::jsonb,
  image text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.offres enable row level security;

create policy "Allow public read offres"
  on public.offres for select
  using ( true );

-- Reservations
create table public.reservations (
  id bigint generated by default as identity primary key,
  reference text unique not null default gen_random_uuid()::text,
  offre_id bigint not null references public.offres(id) on delete cascade,
  nom text not null,
  email text not null,
  date_experience date not null,
  nombre_personnes integer not null,
  prix_total integer not null,
  statut text default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.reservations enable row level security;

create policy "Allow public insert reservations"
  on public.reservations for insert
  with check ( true );

create policy "Allow public read reservations by email"
  on public.reservations for select
  using ( true );

-- Devis requests
create table public.devis_requests (
  id bigint generated by default as identity primary key,
  offre_id bigint references public.offres(id) on delete set null,
  nom text not null,
  email text not null,
  telephone text,
  nombre_personnes integer not null,
  date_souhaitee date,
  message text,
  statut text default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.devis_requests enable row level security;

create policy "Allow public insert devis requests"
  on public.devis_requests for insert
  with check ( true );

create policy "Allow public read devis requests"
  on public.devis_requests for select
  using ( true );

-- Contact messages
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  nom text not null,
  email text not null,
  sujet text not null,
  message text not null,
  statut text default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.contact_messages enable row level security;

create policy "Allow public insert contact messages"
  on public.contact_messages for insert
  with check ( true );

create policy "Allow public read contact messages"
  on public.contact_messages for select
  using ( true );

-- Indexes
create index if not exists idx_offres_village_id on public.offres(village_id);
create index if not exists idx_reservations_offre_id on public.reservations(offre_id);
create index if not exists idx_devis_offre_id on public.devis_requests(offre_id);
create index if not exists idx_villages_slug on public.villages(slug);
create index if not exists idx_offres_slug on public.offres(slug);

-- Storage setup note: use Supabase Storage for images (villages/offres)
